### ISSUE TITLE
CSS: Tags and Categories pages have incorrect spacing of elements when using smaller screens

### ISSUE THREAD

**Issue by TeisybeLT** [TeisybeLT/teisybes_blog#7]
When viewing Tags or Categories pages, there is no space between the tag/category name and its date. This looks unappealing and needs to be fixed. Make it look similar to large-screen layout.

## Reproduction steps
1. Open teisybe.com
2. Navigate to tags or categories page
3. Press F12, and reduce viewport size horizontally or choose a small-screen phone preset

**Comment by JaheimPrice** [comment]
Hello, I'm looking into the issue right now!

I have some ideas to make things work. If needed, may I replace the float properties with an alternate solution?

**Comment by TeisybeLT** [comment]
> Hello, I'm looking into the issue right now!
> 
> I have some ideas to make things work. If needed, may I replace the float properties with an alternate solution?

Yes, of course, whatever fixes the issue.

One thing I'd like to add is that I've used this theme: https://github.com/LordMathis/hugo-theme-nightfall and overloaded some parameters to get it looking the way I want to. You will find the complete list of stylesheets there if you need em'.

**Comment by JaheimPrice** [comment]
Alright thanks! I do not know how reliable I can be especially with doing things as best.

I just started looking into Hugo now, and this is the first time I've come across it. I'll try obeying the framework. Also I'll add that I never used sass before, just looked into CSS preprocessors before.

What I'm already familiar with is usually with responsive design, floats are usually avoided in favor of Flex Box and/or Grids, with a mobile-first approach (as I know it, use media queries to cascade styles to larger screens).

**Comment by TeisybeLT** [comment]
Addressed in commit 8f37869
